services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./data:/app/data  # Add this line to map your data directory
    networks:
      - app-network

  backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/data_stream
    networks:
      - app-network
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
      - ./data:/data

  frontend:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
      - ./data:/data

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
